### ISSUE TITLE
Autocomplete suggestions behind $modelInstance

### ISSUE THREAD

**Issue by bobbyziom** [angular-ui/angular-google-maps#1540]
When using autocomplete places in either header container or modal using bootstrap the suggestions is behind the actual content. 

![Modal geolocation failure](https://dl.dropboxusercontent.com/u/15833598/modalfail.png)

**Comment by nmccready** [comment]
Looks like you might need some CSS wizardry.

**Comment by bobbyziom** [comment]
```css
div.pac-container {
	position: absolute;
	z-index: 10000;
}
```
Fixed it.
