### ISSUE TITLE
twitter bootstrap (CSS) Zoom buttons not displaying properly

### ISSUE THREAD

**Issue by geekarist** [angular-ui/angular-google-maps#925]
When display a map, the zoom buttons are distorted:

![image](https://cloud.githubusercontent.com/assets/1910698/5199162/d1e43d7a-7559-11e4-9423-9e252da567ad.png)

I have to use the following css class to make it work:

``` css
.angular-google-map img {
  max-width: none !important;
}
```
